### ISSUE TITLE
Build fail on android

### ISSUE THREAD

**Issue by khayym** [nilavanraj/react-native-raw#2]
When run app in android this bug happen;

> * Where:
Build file '/Users/khayyam/Desktop/cloud-storage/node_modules/react-native-raw/android/build.gradle' line: 114

> * What went wrong:

A problem occurred evaluating project ':react-native-raw'.
> Expected directory '/Users/khayyam/Desktop/cloud-storage/node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.

**Comment by nilavanraj** [comment]
Hi @khayym, this issue happens in RN0.69+ version so support is added for that in 6300844.  you can use react-native-raw v0.7 for RN0.69 and above.
